-- Lock down PostgREST access: Prisma uses the postgres role (bypasses RLS).
-- anon/authenticated must not read or write application tables directly.

ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Provider" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ParentProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ChildProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Club" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PlannedClub" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TrustedParentConnection" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SharedClub" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SharedClubParticipant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Rating" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ClubChangeRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Notification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "_prisma_migrations" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;
